### ISSUE TITLE
在Linux上使用docker部署，开启GPU加速后，找不到libcudnn_ops_infer.so.8

### ISSUE THREAD

**Issue by RPie06** [Chenyme/Chenyme-AAMT#73]
### 操作系统

Rocky Linux 9

### 项目版本

0.9.0

### Python版本

3.11.9

### 错误描述

请问下使用docker compose在Rocky Linux 9上部署后，开启GPU加速，跑音频和视频都会报错找不到页面是什么问题呢？

![Error](https://github.com/user-attachments/assets/755c63af-bf80-4d28-8979-a038cb28a541)

docker-compose.yaml文件中我添加了以下部分使其能调用到GPU，CUDA版本是12.4，而且在启动好的容器内可以调用nvidia-smi显示GPU信息
```
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
```

补充：
找到原因了，是容器崩了，报错内容如下：
```
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Aborted (core dumped)
```

翻了下之前的issue，Windows版似乎也有过缺少这个dll的问题，linux看来也缺少这个动态库
